export enum CHAT {
    ADD_NEW_MESSAGE = 'CHAT/ADD_NEW_MESSAGE',
    ADD_USER = 'CHAT/ADD_USER',
    ADD_NEW_USER = 'CHAT/ADD_NEW_USER',
    ADD_OTHER_USERS_IN_CHAT = 'CHAT/ADD_OTHER_USERS_IN_CHAT',
}